from .character_matte_extractor import NODE_CLASS_MAPPINGS as C_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as C_DISPLAY_MAPPINGS
from .line_art_extractor import NODE_CLASS_MAPPINGS as L_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as L_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {**C_MAPPINGS, **L_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**C_DISPLAY_MAPPINGS, **L_DISPLAY_MAPPINGS}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
